# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'master_view.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EnSeGi(object):
	def setupUi(self, EnSeGi):
		EnSeGi.setObjectName("EnSeGi")
		EnSeGi.resize(844, 703)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(EnSeGi.sizePolicy().hasHeightForWidth())
		EnSeGi.setSizePolicy(sizePolicy)
		EnSeGi.setMinimumSize(QtCore.QSize(0, 0))
		EnSeGi.setMaximumSize(QtCore.QSize(16777215, 16777215))
		font = QtGui.QFont()
		font.setFamily("Segoe UI")
		font.setPointSize(9)
		EnSeGi.setFont(font)
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Active, QtGui.QIcon.Off)
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
		icon.addPixmap(QtGui.QPixmap(":/newPrefix/icon.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
		EnSeGi.setWindowIcon(icon)
		EnSeGi.setWindowOpacity(10.0)
		EnSeGi.setStyleSheet("")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(EnSeGi)
		self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
		self.verticalLayout_2.setSpacing(0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.vboxlayout_main = QtWidgets.QVBoxLayout()
		self.vboxlayout_main.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
		self.vboxlayout_main.setContentsMargins(0, 0, 0, 0)
		self.vboxlayout_main.setSpacing(2)
		self.vboxlayout_main.setObjectName("vboxlayout_main")
		self.hboxlayout_menubar = QtWidgets.QHBoxLayout()
		self.hboxlayout_menubar.setContentsMargins(1, 1, 1, 1)
		self.hboxlayout_menubar.setSpacing(1)
		self.hboxlayout_menubar.setObjectName("hboxlayout_menubar")
		self.tabwidget_manubar = QtWidgets.QTabWidget(EnSeGi)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.tabwidget_manubar.sizePolicy().hasHeightForWidth())
		self.tabwidget_manubar.setSizePolicy(sizePolicy)
		self.tabwidget_manubar.setMinimumSize(QtCore.QSize(0, 120))
		self.tabwidget_manubar.setTabShape(QtWidgets.QTabWidget.Rounded)
		self.tabwidget_manubar.setTabBarAutoHide(False)
		self.tabwidget_manubar.setObjectName("tabwidget_manubar")
		self.tab_test_automation = QtWidgets.QWidget()
		self.tab_test_automation.setObjectName("tab_test_automation")
		self.toolbutton_run = QtWidgets.QToolButton(self.tab_test_automation)
		self.toolbutton_run.setGeometry(QtCore.QRect(60, 0, 60, 80))
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap(":/newPrefix/button_play_green_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolbutton_run.setIcon(icon1)
		self.toolbutton_run.setIconSize(QtCore.QSize(48, 48))
		self.toolbutton_run.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolbutton_run.setObjectName("toolbutton_run")
		self.toolbutton_load = QtWidgets.QToolButton(self.tab_test_automation)
		self.toolbutton_load.setGeometry(QtCore.QRect(0, 0, 60, 80))
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap(":/newPrefix/folder_48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.toolbutton_load.setIcon(icon2)
		self.toolbutton_load.setIconSize(QtCore.QSize(48, 48))
		self.toolbutton_load.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
		self.toolbutton_load.setObjectName("toolbutton_load")
		self.tabwidget_manubar.addTab(self.tab_test_automation, "")
		self.tab_help = QtWidgets.QWidget()
		self.tab_help.setObjectName("tab_help")
		self.graphicsView = QtWidgets.QGraphicsView(self.tab_help)
		self.graphicsView.setGeometry(QtCore.QRect(56, 0, 50, 50))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
		self.graphicsView.setSizePolicy(sizePolicy)
		self.graphicsView.setMinimumSize(QtCore.QSize(50, 50))
		self.graphicsView.setMaximumSize(QtCore.QSize(50, 50))
		self.graphicsView.setStyleSheet("background-image: url(:/newPrefix/logo_ensegi.png);")
		self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.graphicsView.setObjectName("graphicsView")
		self.graphicsView_2 = QtWidgets.QGraphicsView(self.tab_help)
		self.graphicsView_2.setGeometry(QtCore.QRect(0, 0, 50, 50))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.graphicsView_2.sizePolicy().hasHeightForWidth())
		self.graphicsView_2.setSizePolicy(sizePolicy)
		self.graphicsView_2.setMinimumSize(QtCore.QSize(50, 50))
		self.graphicsView_2.setMaximumSize(QtCore.QSize(50, 50))
		self.graphicsView_2.setStyleSheet("background-image: url(:/newPrefix/logo_toolsgroup.png);")
		self.graphicsView_2.setFrameShape(QtWidgets.QFrame.NoFrame)
		self.graphicsView_2.setObjectName("graphicsView_2")
		self.tabwidget_manubar.addTab(self.tab_help, "")
		self.hboxlayout_menubar.addWidget(self.tabwidget_manubar)
		self.vboxlayout_main.addLayout(self.hboxlayout_menubar)
		self.hboxlayout_testdetails = QtWidgets.QHBoxLayout()
		self.hboxlayout_testdetails.setContentsMargins(1, 1, 1, 1)
		self.hboxlayout_testdetails.setSpacing(1)
		self.hboxlayout_testdetails.setObjectName("hboxlayout_testdetails")
		self.scrollarea_template_details = QtWidgets.QScrollArea(EnSeGi)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.scrollarea_template_details.sizePolicy().hasHeightForWidth())
		self.scrollarea_template_details.setSizePolicy(sizePolicy)
		self.scrollarea_template_details.setMinimumSize(QtCore.QSize(250, 0))
		self.scrollarea_template_details.setStyleSheet("background-color:rgb(255, 255, 255)")
		self.scrollarea_template_details.setWidgetResizable(True)
		self.scrollarea_template_details.setObjectName("scrollarea_template_details")
		self.scrollAreaWidgetContents = QtWidgets.QWidget()
		self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 248, 340))
		self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
		self.label_templatedetails = QtWidgets.QLabel(self.scrollAreaWidgetContents)
		self.label_templatedetails.setGeometry(QtCore.QRect(4, 6, 800, 27))
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_templatedetails.sizePolicy().hasHeightForWidth())
		self.label_templatedetails.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Segoe UI")
		font.setPointSize(9)
		self.label_templatedetails.setFont(font)
		self.label_templatedetails.setText("")
		self.label_templatedetails.setScaledContents(True)
		self.label_templatedetails.setObjectName("label_templatedetails")
		self.label_status = QtWidgets.QLabel(self.scrollAreaWidgetContents)
		self.label_status.setGeometry(QtCore.QRect(210, 148, 32, 32))
		self.label_status.setText("")
		self.label_status.setObjectName("label_status")
		self.label_currenttestcase = QtWidgets.QLabel(self.scrollAreaWidgetContents)
		self.label_currenttestcase.setGeometry(QtCore.QRect(4, 150, 195, 31))
		self.label_currenttestcase.setText("")
		self.label_currenttestcase.setScaledContents(True)
		self.label_currenttestcase.setObjectName("label_currenttestcase")
		self.scrollarea_template_details.setWidget(self.scrollAreaWidgetContents)
		self.hboxlayout_testdetails.addWidget(self.scrollarea_template_details)
		self.tableview_testcaseinfo = QtWidgets.QTableView(EnSeGi)
		self.tableview_testcaseinfo.setFrameShape(QtWidgets.QFrame.WinPanel)
		self.tableview_testcaseinfo.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.tableview_testcaseinfo.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
		self.tableview_testcaseinfo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
		self.tableview_testcaseinfo.setGridStyle(QtCore.Qt.SolidLine)
		self.tableview_testcaseinfo.setObjectName("tableview_testcaseinfo")
		self.tableview_testcaseinfo.horizontalHeader().setHighlightSections(False)
		self.tableview_testcaseinfo.horizontalHeader().setStretchLastSection(True)
		self.tableview_testcaseinfo.verticalHeader().setVisible(False)
		self.hboxlayout_testdetails.addWidget(self.tableview_testcaseinfo)
		self.vboxlayout_main.addLayout(self.hboxlayout_testdetails)
		self.textbrowser_summary = QtWidgets.QTextBrowser(EnSeGi)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.textbrowser_summary.sizePolicy().hasHeightForWidth())
		self.textbrowser_summary.setSizePolicy(sizePolicy)
		font = QtGui.QFont()
		font.setFamily("Segoe UI")
		font.setPointSize(9)
		self.textbrowser_summary.setFont(font)
		self.textbrowser_summary.setStyleSheet("background-color: rgb(255, 255, 255)")
		self.textbrowser_summary.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.textbrowser_summary.setFrameShadow(QtWidgets.QFrame.Sunken)
		self.textbrowser_summary.setObjectName("textbrowser_summary")
		self.vboxlayout_main.addWidget(self.textbrowser_summary)
		self.progressbar_execution = QtWidgets.QProgressBar(EnSeGi)
		self.progressbar_execution.setProperty("value", 24)
		self.progressbar_execution.setTextVisible(False)
		self.progressbar_execution.setObjectName("progressbar_execution")
		self.vboxlayout_main.addWidget(self.progressbar_execution)
		self.vboxlayout_main.setStretch(3, 1)
		self.verticalLayout_2.addLayout(self.vboxlayout_main)

		self.retranslateUi(EnSeGi)
		self.tabwidget_manubar.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(EnSeGi)

	def retranslateUi(self, EnSeGi):
		_translate = QtCore.QCoreApplication.translate
		EnSeGi.setWindowTitle(_translate("EnSeGi", "EnSeGi"))
		self.toolbutton_run.setText(_translate("EnSeGi", "Run"))
		self.toolbutton_load.setText(_translate("EnSeGi", "Load"))
		self.tabwidget_manubar.setTabText(self.tabwidget_manubar.indexOf(self.tab_test_automation), _translate("EnSeGi", "Test Automation"))
		self.tabwidget_manubar.setTabText(self.tabwidget_manubar.indexOf(self.tab_help), _translate("EnSeGi", "Help"))

import app.presenter.view.images_used_rc
